[project]
name = "fk-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]
